### PR TITLE
outer-height.js/outer-width.js - element width and height calculation helpers (IE8+ support)

### PR DESCRIPTION
**Pull request by SilentCicero**
http://youmightnotneedjquery.com/#outer_height_with_margin
http://youmightnotneedjquery.com/#outer_width_with_margin

-- IE8 supported versions of these methods [jQuery standard+]

### CODE REVIEW

**Comment by SilentCicero** [comment]
@rstacruz great work on this package ! - let me know what you think. Would really like to get outerHeight into this package ASAP.

Best,
Nick

**Comment by rstacruz** [comment]
Heh, I see you had to edit that a few times :)

**Comment by rstacruz** [comment]
It looks like you're using `marginleft` instead of `marginLeft`. Let me fix that for you.

**Comment by rstacruz** [comment]
Released in 1.3.0. Thanks!

**Comment by SilentCicero** [comment]
@rstacruz lol. Yeah I had to do a few edits/experiments to pass the linting/compat tests. Great catch on the marginLeft. Thanks ! Awesome package.

**Pull request merged**
